# Optimal Hyperparameters for Polaris ADME Benchmark across ChemLlama scales

170m:
  model_name: "yerevann/chemllama-170m"
  backbone_lr: 1.582314271119698e-5
  batch_size: 16
  head_lr: 3.139289401685766e-5
  mlp_hidden_size: 256
  n_unfreeze: 8
  pooling: "last_token"
  weight_decay: 0.001
  dropout: 0.1
  warmup_ratio: 0.1
  epochs: 10

380m:
  model_name: "yerevann/ChemLlama-380M"
  backbone_lr: 3.546940123587843e-5
  batch_size: 16
  head_lr: 0.006462823994896947
  mlp_hidden_size: 512
  n_unfreeze: 16
  pooling: "last_token"
  weight_decay: 0.2
  dropout: 0.1
  warmup_ratio: 0.1
  epochs: 10

1b:
  model_name: "yerevann/ChemLlama-1B"
  backbone_lr: 1.537078452573621e-5
  batch_size: 16
  head_lr: 0.00046456062804424274
  mlp_hidden_size: 512
  n_unfreeze: 16
  pooling: "last_token"
  weight_decay: 0.15
  dropout: 0.1
  warmup_ratio: 0.1
  epochs: 10

3b:
  model_name: "yerevann/ChemLlama-3B"
  backbone_lr: 9.77686576038078e-6
  batch_size: 32
  head_lr: 4.566959756306205e-5
  mlp_hidden_size: 512
  n_unfreeze: 24
  pooling: "last_token"
  weight_decay: 0.25
  dropout: 0.1
  warmup_ratio: 0.1
  epochs: 10
